version: "3.8"

services:
  ngrok:
    image: ngrok/ngrok:latest
    container_name: ngrok_tunnel
    command: http n8n:5678 --url=strictly-main-eagle.ngrok-free.app
    environment:
      - NGROK_AUTHTOKEN=2vUdEOZW98hc4kjyCc0PbJMQGiN_3Bc5NowwXdwkUTV9kZUQZ  # Replace with your Ngrok auth token
    restart: unless-stopped
    networks:
      - n8n_network

  n8n:
    image: n8nio/n8n:latest
    container_name: flamboyant_benz
    restart: always
    user: "node"
    ports:
      - "5678:5678"
    volumes:
      - .n8n:/home/node/.n8n
    environment:
      - N8N_SECURE_COOKIE=false
      - GENERIC_TIMEZONE=Asia/Ho_Chi_Minh
      - N8N_EDITOR_BASE_URL=https://strictly-main-eagle.ngrok-free.app
      - WEBHOOK_URL=https://strictly-main-eagle.ngrok-free.app
      - N8N_DEFAULT_BINARY_DATA_MODE=filesystem
      - NODE_VERSION=20.18.2
      - YARN_VERSION=1.22.22
      - NODE_ICU_DATA=/usr/local/lib/node_modules/full-icu
      - N8N_VERSION=1.78.1
      - NODE_ENV=production
      - N8N_RELEASE_TYPE=stable
      - N8N_COMMUNITY_PACKAGES_ALLOW_TOOL_USAGE=true
      - SHELL=/bin/sh
    entrypoint:
      - "tini"
      - "--"
      - "/docker-entrypoint.sh"
    networks:
      - n8n_network

networks:
  n8n_network:
    driver: bridge
