version: "3.8"

services:
  n8n:
    image: n8nio/n8n:latest
    container_name: cont_n8n
    environment:
      - N8N_SECURE_COOKIE=false
      - GENERIC_TIMEZONE=Asia/Ho_Chi_Minh
      - N8N_EDITOR_BASE_URL=${NGROK_URL}
      - WEBHOOK_URL=${NGROK_URL}
      - N8N_DEFAULT_BINARY_DATA_MODE=filesystem
      - N8N_COMMUNITY_PACKAGES_ALLOW_TOOL_USAGE=true
    ports:
      - "5678:5678"
    volumes:
      - ./vol_n8n:/home/node/.n8n
    restart: unless-stopped
    depends_on:
      - ngrok
    networks:
      - n8n_network

  ngrok:
    image: ngrok/ngrok:latest
    container_name: cont_ngrok
    command: http n8n:5678 --url=${NGROK_URL}
    environment:
      - NGROK_AUTHTOKEN=${NGROK_AUTHTOKEN}
      - NGROK_REGION=ap # or 'us', 'eu', etc.
    restart: unless-stopped
    networks:
      - n8n_network
networks:
  n8n_network:
    driver: bridge
